### ISSUE TITLE
你好，我是一名大二学生，想学习一下tp，但是下载源码放在wamp里运行报错，请问可以给一下数据库导出的sql文件吗？

### ISSUE THREAD

**Issue by Abel676** [mayuko2012/tech2day#2]

**Comment by liopoos** [comment]
你好，SQL文件在[tech2day.sql](https://cdn.mayuko.cn/sql/tech2day.sql)中，祝你学习进步。

**Comment by Abel676** [comment]
谢谢师兄

**Comment by Abel676** [comment]
你好师兄，抱歉再次打扰，数据库录入之后可以成功运行起来，但是好了少了一些css样式文件，请问去哪里下载呢？

**Comment by liopoos** [comment]
> 你好师兄，抱歉再次打扰，数据库录入之后可以成功运行起来，但是好了少了一些css样式文件，请问去哪里下载呢？


样式使用了bootstrap，请看一些public/下的资源是否存在
